### ISSUE TITLE
Adequar ao padrões recomendados pela comunidade

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#5]
**Descreva a solução que gostaria**

O github  recomenda fortemente que todo projeto siga alguns princípios para que sua comunidade consiga contribuir tranquilamente com o projeto. Assim, gostaria de propor que este projeto siga o padrão proposto pela comunidade. 

**Funcionalidades requeridas**
- [x] Issue template
- [x] Descrição
- [x] Código de conduta
- [x] Guia de contribuição
- [x] Licença
- [x] Template de pull request

**Contexto Adicional**
Community profile do projeto: https://github.com/fga-eps-mds/2019.2-Grupo6/community

**Comment by Bumbleblo** [comment]
@mateusnr referencie as suas contribuições com esse épico via issue
