### ISSUE TITLE
Escrever documentação necessária do projeto

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Alohomora#66]
**Descreva a solução que gostaria**

Escrever uma série de documentos que mostrem vários aspectos do projeto visando viabilidade.

**Funcionalidades requeridas**

- [x] EAP
- [x] TAP
- [ ] Documentos de riscos
- [ ] Roadmaps
- [ ] Documentos de custos
- [ ] Historico de Sprints reviews
- [ ] Historicos de plannings
